// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PotteryClass.Data;

namespace PotteryClass.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410212108_AddAssignmentTeamFinalSubmission")]
    partial class AddAssignmentTeamFinalSubmission
    {
    }
}
