// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PotteryClass.Data;

namespace PotteryClass.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514120000_AddCriterionCategory")]
    partial class AddCriterionCategory
    {
    }
}
